# Generated by Django 5.0.3 on 2024-03-25 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bheem', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='myupload',
            new_name='MyFileUpload',
        ),
        migrations.RenameField(
            model_name='myfileupload',
            old_name='File_name',
            new_name='file_name',
        ),
        migrations.RenameField(
            model_name='myfileupload',
            old_name='my_FIle',
            new_name='my_file',
        ),
    ]
